server:
  port: 9087
spring:
  datasource:
    url: jdbc:mysql://182.61.10.117:3306/rongyun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Jiayouxl2012@
    username: root
mybatis:
  type-aliases-package: com.xl.model
